### ISSUE TITLE
Use  real time API to provide up to date news

### ISSUE THREAD

**Issue by OGKevin** [GoogleChromeLabs/go-hackernews#3]
Hi,

I've been visiting your project almost daily and I've noticed that the entries that are shown are not up to date. It seems that it has never updated since the first time I've visited 🤔 

e.g. compare it to https://vue-hn.now.sh/top or https://news.ycombinator.com/

**Comment by navigaid** [comment]
Every project built with hnpwa.com's api behaves this way. This issue is not exclusive to the project.

**Comment by OGKevin** [comment]
Then I highly recommend using https://github.com/HackerNews/API as this is more real-time. 

Else i don't really see the point in using this implementation of hacker news :( Happy to help tho :)

**Comment by housseindjirdeh** [comment]
Yep @OGKevin, the API's update rate isn't nearly as frequent as the official one (plus we're just making REST calls at the moment so there is no real-time functionality)

A problem with the official API is that every story item only list's the IDs of each comment, and the same for each comment and their children. It makes it virtually unusable when just making REST requests because hundreds of requests are needed just to load a single story.

I would definitely be open to plugging in [Firebase](https://firebase.google.com/docs/web/setup) and using a websocket to make things real time. My only concern is that it might bloat up our application. The Vue HN implementation mitigates this by SSR if I'm not mistaken. Definitely open to seeing how we can do something similar here :)

**Comment by OGKevin** [comment]
> It makes it virtually unusable when just making REST requests because hundreds of requests are needed just to load a single story.

understandable, but they my question is why would this make it unusable what's wrong with making these hundred requests? e.g. rate limit? All the load will be on HN's servers, right?

I might be naive but, why would someone provide an unusable API? 😅
